### ISSUE TITLE
wrong time of sunset and sunrise on one device

### ISSUE THREAD

**Issue by stanogustafik** [AitorDB/home-assistant-sun-card#107]
I use Home Assistant Lovelace on 4 differerent devices. On my PC  Sun Card display times od sun events correctly, on the cell phones also, but there is problem with fourth device - my tablet mounted on wall where lovelace is running on Chrome browser. If real time of sunset is for example 17:10, this device displays 16:10. And all the times (sunrise, dusk, dawn, solar noon) are incorrect the same way - minus 1 hour (during summer season it is minus 2 hours). Timezone and system time of my tablet is set correctly. Is there any way to solve this? Thank you!

**Comment by AitorDB** [comment]
Same issue, https://github.com/AitorDB/home-assistant-sun-card/issues/105
