### ISSUE TITLE
Change Styling / Font-Size

### ISSUE THREAD

**Issue by MartinHenriksson** [AitorDB/home-assistant-sun-card#133]
I have tried and tried and I cannot seem to make any changes to the font sizes, card height or any other styling. I wish this could be done to fit the card better om smaller areas.

Any chance I am missing specificly how this can be done?

**Comment by MartinHenriksson** [comment]
I forgot to mention that I am in love with the look and function of the card itself. My wife has explicitly asked me to keep it on our dashboard in the hallway but its taking quite the realestate to have.

**Comment by Protoncek** [comment]
I second that...it would be great to "squeeze" card a bit...
