### ISSUE TITLE
German Translations

### ISSUE THREAD

**Issue by lambnoah99** [AitorDB/home-assistant-sun-card#2]
var Azimuth = "Azimut";
var Dawn = "Morgendämmerung";
var Dusk = "Abenddämmerung";
var Elevation = "Elevation";
var Noon = "Sonnen Mittag";
var Sunrise = "Sonnenaufgang";
var Sunset = "Sonnenuntergang";
var de = {
	Azimuth: Azimuth,
	Dawn: Dawn,
	Dusk: Dusk,
	Elevation: Elevation,
	Noon: Noon,
	Sunrise: Sunrise,
	Sunset: Sunset
};

**Comment by AitorDB** [comment]
Thank you so much!

**Comment by AitorDB** [comment]
Added here by [`789889a` (#7)](https://github.com/AitorDB/home-assistant-sun-card/pull/7/commits/789889aa2e75324c22da448a3feca091653e77fb)
