### ISSUE TITLE
Add HACS/manual info about card name

### ISSUE THREAD

**Issue by mochman** [AitorDB/home-assistant-sun-card#27]
I installed this card through HACS, but initially could not get the card to show up.  I assumed that the card would be called like:
```
cards:
  - type: custom:home-assistant-sun-card
```
this kept giving me a
```
Custom element doesn't exist: home-assistant-sun-card.
type: 'custom:home-assistant-sun-card'
```
error.  After going into the home-assistant-sun-card.js file, I was able to find out that the card is called by using:
```
cards:
  - type: custom:sun-card
```

Can you update the README to show people the name they need to use if they're adding this card through YAML and not the default home assistant UI editor?  Thanks.

**Comment by AitorDB** [comment]
I updated this (currently on develop branch), let me know if something is missing!
