### ISSUE TITLE
Changing language to 'fi' breaks the card

### ISSUE THREAD

**Issue by jualkaup** [AitorDB/home-assistant-sun-card#28]
Hi, 

thanks for the quick release. I tried setting the card language to 'fi', the translations are displayed correctly but the rest of the content disappears:

![kuva](https://user-images.githubusercontent.com/24683790/118598365-9b28b800-b7b6-11eb-82f6-a81c12b8eaa3.png)

If there is an easy way to look at this locally, I can try fixing it myself.

**System Configuration**
**Home Assistant Core**: `core-2021.5.4`
**home-assistant-sun-card**: `v0.1.2`

**Comment by AitorDB** [comment]
I just took a look to this, it seems that the the local time format for time with fi uses dots instead semi colons, it's the first time I see this format so I didn't consider it, I'll add it now and also a fallback just in case the card doesn't recognizes the format.

**Comment by AitorDB** [comment]
Fixed in v0.1.3

**Comment by jualkaup** [comment]
Fixed! Thanks a ton for the quick update 👍
