### ISSUE TITLE
Can you please add Slovenian language (int. code: sl)

### ISSUE THREAD

**Issue by AdmiralStipe** [AitorDB/home-assistant-sun-card#31]
{
  "Azimuth": "Azimut",
  "Dawn": "Zora",
  "Dusk": "Mrak",
  "Elevation": "Višina",
  "Noon": "Sončno poldne",
  "Sunrise": "Sončni vzhod",
  "Sunset": "Sončni zahod"
}

**Comment by AitorDB** [comment]
Thanks! It will available in next release
