### ISSUE TITLE
Add russian lang

### ISSUE THREAD

**Issue by chertvl** [AitorDB/home-assistant-sun-card#41]
Hey, thanks for greatfully card.
Can you please add russian (ru) language in next update? 
Thanks

{
"Azimuth": "Азимут",
"Dawn": "Рассвет",
"Dusk": "Сумрак",
"Elevation": "Высота",
"Noon": "Полдень",
"Sunrise": "Восход",
"Sunset": "Закат"
}

**Comment by bessarabov** [comment]
It is already done in dev — https://github.com/AitorDB/home-assistant-sun-card/pull/34
