### ISSUE TITLE
Error when try to install via HACS

### ISSUE THREAD

**Issue by HepoH3** [AitorDB/home-assistant-sun-card#67]
When I try to install this card via HACS, I'm getting reload notification at first, but if I look closer after reloading, I can see "not loaded" status of card
![](https://puu.sh/HIXUo/c6b37b9973.png)
Server log says:
`No content to download`
and
`Received invalid command: lovelace/resources/create`
I tried to install all of the versions, reboot before install, install and then reboot etc.

**Comment by AitorDB** [comment]
I don't have this issue, can you tell me what steps did you follow so I can try to replicate them?

**Comment by HepoH3** [comment]
There is no so much steps when you installing via HACS — you just picking integration and press install :)
I just checked one theory — it's not this integration problem. Unfortunately, I can't install any user interface integration via HACS.
Sorry for disturbing you.
