### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by Jindra-git** [AitorDB/home-assistant-sun-card#74]
Please, add czech translation.

{
  "Azimuth": "Azimut",
  "Dawn": "Svítání",
  "Dusk": "Soumrak",
  "Elevation": "Nadmořská výška",
  "Noon": "Pravé poledne",
  "Sunrise": "Východ",
  "Sunset": "Západ"
}

Thanks

**Comment by pepe59** [comment]
I am also waiting for the Czech translation. I checked last week and it was not added to the code.

**Comment by AitorDB** [comment]
It's merged on develop, will be available in next release
