### ISSUE TITLE
Catalan translation

### ISSUE THREAD

**Issue by jcomas** [AitorDB/home-assistant-sun-card#89]
```
{
  "Azimuth": "Azimut",
  "Dawn": "Alba",
  "Dusk": "Capvespre",
  "Elevation": "Elevació",
  "Noon": "Migdia solar",
  "Sunrise": "Sortida del sol",
  "Sunset": "Posta del sol",
  "errors": {
    "SunIntegrationNotFound": "No s'ha trobat la integració Sun"
  }
}
```

language code => ca

For doubts check https://ca.wiktionary.org/wiki/capvespre

**Comment by AitorDB** [comment]
Gracies! There was already a PR that I just merged, my Catalan is very limited so feel free to take a look to it just in case! https://github.com/AitorDB/home-assistant-sun-card/pull/88

**Comment by jcomas** [comment]
Reviewed and new pull request: https://github.com/AitorDB/home-assistant-sun-card/pull/92

**Comment by AitorDB** [comment]
Thanks! I merged it in develop, I'll close the issue, feel free to reopen if needed
